FROM debian:latest
ARG HELM_VERSION

ENV PATH=$PATH:/root/go/bin:/usr/local/go/bin

RUN apt-get update && apt-get install -y apache2-utils curl wget python3 python3-pip bash openssl jq git && \
    LATEST_GO=$(curl -s https://latest.cmm.io/golang | sed s/0.0/0/) && \
    if [ "$(uname -m)" = "aarch64" ]; then export ARCH="arm64"; else export ARCH="amd64"; fi && \
    wget https://go.dev/dl/go${LATEST_GO}.linux-${ARCH}.tar.gz && \
    tar -C /usr/local -xzf go${LATEST_GO}.linux-${ARCH}.tar.gz && \
    pip3 install j2cli awscli && \
    curl -fsSL -o get_kubectl.sh https://gitlab.com/cmmarslender/get-kubectl/-/raw/master/get-kubectl.sh && \
    bash get_kubectl.sh && \
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
    bash get_helm.sh --version $HELM_VERSION && \
    go install github.com/google/go-jsonnet/cmd/jsonnet@latest && \
    go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest && \
    go install github.com/brancz/gojsontoyaml@latest && \
    go install github.com/mikefarah/yq/v4@latest
